site_name: Math 2024/25 Winter
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
markdown_extensions:
  - toc
  - tables
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - macros  # Optional, for template macros
  - mkdocstrings
extra_css:
  - styles/extra.css  # Optional, for custom styling

extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
